'use client';
import { useEffect, useState } from 'react';
const campo='w-full rounded-md border border-linea bg-white px-3 py-2 text-sm focus:border-oro-claro focus:outline-none';
export function NutricionClinicaForm({ pacienteId }: { pacienteId: string }) {
  const [d,setD]=useState<any>(null),[mensaje,setMensaje]=useState(''),[guardando,setGuardando]=useState(false);
  useEffect(()=>{fetch(`/api/pacientes/${pacienteId}/nutricion`).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setD(b)}).catch(e=>setMensaje(e.message))},[pacienteId]);
  async function guardar(confirmado:boolean){setGuardando(true);const r=await fetch(`/api/pacientes/${pacienteId}/nutricion`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...d,confirmado})});const b=await r.json();setMensaje(r.ok?(confirmado?'Plan nutricional confirmado.':'Borrador guardado.'):(b.error??'No se pudo guardar.'));if(r.ok)setD({...d,confirmado});setGuardando(false)}
  if(!d)return <p className="text-sm text-choco-soft">{mensaje||'Cargando nutrición…'}</p>;
  return <div><p className="mb-1 text-[9.5px] font-semibold uppercase tracking-[0.18em] text-oro">Paso 9</p><h2 className="mb-1 font-serif text-2xl text-choco-deep">Nutrición</h2><p className="mb-5 text-xs text-choco-soft">Plan individualizado alineado a la fase {d.fase}. No se completa automáticamente desde libros.</p><section className="space-y-4 rounded-card border border-linea bg-white p-5"><label className="block text-sm">Priorizar<textarea rows={5} className={`${campo} mt-1`} value={d.priorizar} onChange={e=>setD({...d,priorizar:e.target.value,confirmado:false})}/></label><label className="block text-sm">Evitar<textarea rows={5} className={`${campo} mt-1`} value={d.evitar} onChange={e=>setD({...d,evitar:e.target.value,confirmado:false})}/></label><label className="block max-w-xs text-sm">Comidas por día<input type="number" min={1} max={10} className={`${campo} mt-1`} value={d.comidasDia} onChange={e=>setD({...d,comidasDia:Number(e.target.value),confirmado:false})}/></label><p className="text-xs text-choco-soft">La fórmula magistral {d.tieneFormula?'está firmada.':'aún no está firmada.'}</p></section>{mensaje&&<p className="mt-3 text-sm">{mensaje}</p>}<div className="mt-4 flex gap-2"><button disabled={guardando} onClick={()=>guardar(false)} className="rounded-md border border-linea-fuerte px-5 py-2.5 text-sm">Guardar borrador</button><button disabled={guardando||!d.priorizar||!d.evitar} onClick={()=>guardar(true)} className="rounded-md bg-choco-deep px-5 py-2.5 text-sm text-crema disabled:opacity-40">Confirmar plan</button></div></div>;
}
