import { NextRequest, NextResponse } from 'next/server';
import { z } from 'zod';
import { createClient } from '@/lib/supabase/server';
import { evaluarControl, MAX_REFORMULACIONES_CONSECUTIVAS } from '@/lib/algoritmo/criterios-avance';
import { FASES, type Fase } from '@/lib/algoritmo/fases';

const Schema=z.object({reduccionIptPct:z.number().min(-100).max(100),mejoriaObjetivosPct:z.number().min(-100).max(100),adherenciaPct:z.number().min(0).max(100),semanasEnFase:z.number().int().min(0).max(520),banderaRojaNueva:z.boolean()});
async function contexto(id:string){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{error:NextResponse.json({error:'No autenticado'},{status:401})};const {data:u}=await supabase.from('usuarios').select('tenant_id').eq('auth_id',user.id).maybeSingle();const tenantId=(u as any)?.tenant_id;const {data:p}=await supabase.from('pacientes').select('id').eq('id',id).eq('tenant_id',tenantId).is('deleted_at',null).maybeSingle();if(!tenantId||!p)return{error:NextResponse.json({error:'Paciente no encontrado'},{status:404})};return{supabase,tenantId}}
export async function GET(_r:NextRequest,{params}:{params:Promise<{id:string}>}){const{id}=await params;const ctx=await contexto(id);if('error'in ctx)return ctx.error;const [fase,controles]=await Promise.all([ctx.supabase.from('fases_terapeuticas').select('fase_seleccionada,confirmado').eq('paciente_id',id).eq('tenant_id',ctx.tenantId).maybeSingle(),ctx.supabase.from('controles_clinicos').select('*').eq('paciente_id',id).eq('tenant_id',ctx.tenantId).order('created_at',{ascending:false})]);if(fase.error||controles.error)return NextResponse.json({error:fase.error?.message??controles.error?.message},{status:500});const f=fase.data as any;if(!f?.confirmado)return NextResponse.json({error:'Confirme primero la fase terapéutica.'},{status:409});const rows=(controles.data??[]) as any[];return NextResponse.json({fase:f.fase_seleccionada,cicloNum:rows.length+1,reformulacionesPrevias:rows.filter(x=>x.decision==='reformular').slice(0,MAX_REFORMULACIONES_CONSECUTIVAS).length,historial:rows});}
export async function POST(req:NextRequest,{params}:{params:Promise<{id:string}>}){const{id}=await params;const ctx=await contexto(id);if('error'in ctx)return ctx.error;const parsed=Schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:'Valores de control inválidos.'},{status:422});const [fase,prev]=await Promise.all([ctx.supabase.from('fases_terapeuticas').select('fase_seleccionada,confirmado').eq('paciente_id',id).eq('tenant_id',ctx.tenantId).maybeSingle(),ctx.supabase.from('controles_clinicos').select('decision').eq('paciente_id',id).eq('tenant_id',ctx.tenantId).order('created_at',{ascending:false})]);const f=(fase.data as any)?.fase_seleccionada as Fase;if(!(fase.data as any)?.confirmado||!f)return NextResponse.json({error:'Confirme primero la fase.'},{status:409});const rows=(prev.data??[]) as any[];const reformulaciones=rows.filter(x=>x.decision==='reformular').slice(0,MAX_REFORMULACIONES_CONSECUTIVAS).length;const resultado=evaluarControl(parsed.data,f,FASES[f].semanasMinimas,reformulaciones);const{error}=await(ctx.supabase.from('controles_clinicos')as any).insert({tenant_id:ctx.tenantId,paciente_id:id,fase:f,ciclo_num:rows.length+1,reduccion_ipt_pct:parsed.data.reduccionIptPct,mejoria_objetivos_pct:parsed.data.mejoriaObjetivosPct,adherencia_pct:parsed.data.adherenciaPct,semanas_en_fase:parsed.data.semanasEnFase,bandera_roja_nueva:parsed.data.banderaRojaNueva,reformulaciones_previas:reformulaciones,decision:resultado.decision});return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({ok:true,resultado});}
